### ISSUE TITLE
Floor needs more methods 

### ISSUE THREAD

**Issue by BUNQNF** [MoeyyadQuresh/ChamberCrawler3000#13]
moveEnermies: to be called after each move
 printMessage(Character*,string action): to be called immediately after each printFloor

Also can control() give a return code so that main() knows if the player meets something/somebody or tried to pass something not passable. (Figure 4)

**Comment by CaveExplorer256** [comment]
I'll give every Character (Player and NPC) an update() method. update() can handle everything that happens when it's a Character's turn to act and only runs if it hasn't been run during the current turn.
Calling update() could cover moving enemies for NPCs. It might do nothing for Player if all Player actions happen before NPCs.

printMessage might be something for a Player method. We can discuss it tomorrow along with the kind of values control() should return.
